language: c
sudo: false # only for faster builds
compiler: 
 - clang
 - gcc
 script:
 - gcc -o test pyramid.c // we can use gcc instead of clang too
 - ./test 
 - gcc -o test reverse_pyramid.c // we can use gcc instead of clang too
 - ./test 
 - gcc -o test digit_p.c // we can use gcc instead of clang too
 - ./test 
 - gcc -o test Dimond.c // we can use gcc instead of clang too
 - ./test 
